dist: xenial
os:  
  - linux-ppc64le
sudo: required

language: go
go:
  - "1.9.4"
  
script:
   - cd $GOPATH/src/github.com
  - mkdir kiali
  - cd kiali
  - git clone https://github.com/kiali/kiali.git
  - cd kiali
  - sudo make dep-install
  - sudo make build
  - sudo make test
