os:  
  - linux-ppc64le
sudo: required

script:
  - export GOPATH=/source/kiali/kiali
  - mkdir -p $GOPATH
  - cd $GOPATH
  - mkdir -p src/github.com/kiali
  - cd src/github.com/kiali
  - git clone git@github.com:kiali/kiali
  - export PATH=${PATH}:${GOPATH}/bin
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - make dep-install
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - make dep-update
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - make build
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - make test

