os: linux
arch: ppc64le
dist: bionic
language: go
sudo: required
  
#services:
#- docker

go: 1.14.x

install:
 - sudo add-apt-repository 'deb https://oplab9.parqtec.unicamp.br/pub/repository/debian/ ./'
 - wget https://oplab9.parqtec.unicamp.br/pub/key/openpower-gpgkey-public.asc
 - sudo apt-key add openpower-gpgkey-public.asc
 - sudo apt update
 - sudo apt install glide
 #- wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/glide/glide-0.13.3
 #- mv glide-0.13.3 glide
 #- sudo chmod 755 glide
 #- sudo mv glide /usr/bin/glide

before_script:
  - cd $GOPATH/src/github.com
  - mkdir kiali
  - cd kiali
  - git clone https://github.com/kiali/kiali.git
  - cd kiali 
  - rm Makefile
  - mv /home/travis/gopath/src/github.com/Unicamp-OpenPower/kiali-build/Makefile $GOPATH/src/github.com/kiali/kiali/Makefile

script:
  - make build
  - make test

notifications:
  slack:
    rooms:
      - secure: "aPEo+OioLm9K7560mNLUus7GFxl77CiOUnADo2JF/8WVv16bWvzHF1FgLlFvEGZsQSV860UfpIq2XagtXqnhEgvO5l/u6cytoX5fYtlHfEvppCzBOnj5wBhET7ViQeFdXzaqmMd6OEq/i4lQJ4+qCfMf4VZkwyJtxUMsE4UlWeQbeRRUI3oCYv0zy2cpIVKXZRXIv9ZYG/gk/GLbQjkTJD7uo3xyhKAXpx7OQQVvTpjZlTZ8Ehrfndxyh5xVpq2scbDn8+AKbV2f6GHrNlP89HXd/mM5FyTYEVGFIk0PD2es00qZnyiAVpWQWExLXCk4QC4OtpQAJvo5VFNCT15LkrSyvGXKgu93+kc6UGJTCeBnU8xYb/v+94JET1LS25s4CEY6Ng87vnlkUgoNIr2r/dhPBQsWofodKG54mvblqpsHGJhC3/5+/4QY6FuegknI8zmjTxlcydVfCuCjfGjSDtoVwhDdte5v7MnPwenb9PfUM3FREPy6x3sTkJuCu0sUntn4CgFhcc8AI3iFcjbcKT8N/AwmSqOzjDrSMJa8iNS34vbO/B8zITLU5tMrw8EglSj0HROv1FpC786dpJ+PfuDYXZ8gjHjgdYMh5rEJTSNOKppilGDFG6oYIKhIBgqQXft6nZTmjYZx9imfH7ctd/M/zvDjaZg4+SU7k554CKQ="
    on_success: change
    on_failure: change
