dist: xenial
os:  
  - linux-ppc64le
sudo: required

before_install:
  - sudo apt-get update
  - wget https://dl.google.com/go/go1.9.4.linux-ppc64le.tar.gz
  - sudo tar -xvf go1.11.4.linux-amd64.tar.gz
  - sudo mv go /usr/local
  - export GOROOT=/usr/local/go
  
script:
  - export GOPATH=/source/kiali/kiali
  - sudo mkdir -p $GOPATH
  - cd $GOPATH
  - sudo mkdir -p src/github.com/kiali
  - cd src/github.com/kiali
  - sudo git clone https://github.com/kiali/kiali.git
  - export PATH=${PATH}:${GOPATH}/bin
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - sudo make dep-install
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - sudo make dep-update
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - sudo make build
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - sudo make test

