os:  
  - linux-ppc64le
sudo: required

script:
  - export GOPATH=/source/kiali/kiali
  - sudo mkdir -p $GOPATH
  - cd $GOPATH
  - sudo mkdir -p src/github.com/kiali
  - cd src/github.com/kiali
  - sudo git clone git@github.com:kiali/kiali
  - export PATH=${PATH}:${GOPATH}/bin
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - sudo make dep-install
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - sudo make dep-update
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - sudo make build
  - cd ${GOPATH}/src/github.com/kiali/kiali
  - sudo make test

